apiVersion: 1

datasources:
  - name: ClickHouse (events)
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    uid: clickhouse_events
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: ${CLICKHOUSE_DB}
      username: ${CLICKHOUSE_USER}
      queryTimeout: 0
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}

