apiVersion: 1

datasources:
  - name: ClickHouse (events)
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    uid: clickhouse_events
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: ${CLICKHOUSE_DB}
      username: ${CLICKHOUSE_USER}
      # В некоторых версиях clickhouse datasource клиент пытается выставлять max_execution_time.
      # queryTimeout=0 отключает установку таймаута на стороне клиента и убирает частый "failed to create ClickHouse client".
      queryTimeout: 0
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
